#!/bin/sh
set -e
RAM=/dev/shm/firefox-kevin
DISK=/home/kevin/.mozilla/firefox/a8o3uubf.kevin-1706213665373.disk
if [ -d "$RAM" ] && [ -d "$DISK" ]; then
    rsync -a --delete \
        --exclude='storage/default/https*cache*' \
        --exclude='crashes' \
        --exclude='minidumps' \
        --exclude='saved-telemetry-pings' \
        "$RAM/" "$DISK/"
    chown -R kevin:kevin "$DISK"
fi
