t playlist-shuffle

RIGHT  seek   5 exact
LEFT   seek  -5 exact
UP     seek  60 exact
DOWN   seek -60 exact

# Optional: scroll wheel to zoom
WHEEL_UP add video-zoom 0.1
WHEEL_DOWN add video-zoom -0.1

F1 script-binding console/enable

# Zoom in/out
Alt+f add video-zoom  0.25
Alt+c add video-zoom -0.25

# Pan video using Alt + Arrow Keys
Alt+w  add video-pan-y -0.05
Alt+s  add video-pan-y  0.05
Alt+a  add video-pan-x -0.05
Alt+d  add video-pan-x  0.05

# Reset zoom and pan back to default
Alt+z set video-zoom 0; set video-pan-x 0; set video-pan-y 0;
