volume-max=300
sub-font='Ubuntu Sans'
sub-color='#FFA500'
sub-border-color='#000000'
sub-border-size=3.0
sub-shadow-offset=0
sub-shadow-color='#00000000' # Fully transparent (effectively disabling shadow)
vo=gpu
gpu-api=opengl
hwdec=vaapi
border=no

ytdl-format=bestvideo[height<=720]+bestaudio/best[height<=720]
geometry=960x50%
keepaspect=yes
sub-font='Noto Sans,Noto Color Emoji'
sub-font-provider=fontconfig

[audio-no-video]
profile-cond = (filename:match("%.mp3$") ~= nil)
vo = null
