#!/usr/bin/env lua

local home = os.getenv("HOME")
package.path = package.path .. ";" .. home .. "/.config/creek/?.lua"

local actions = require("modules.actions")

local rune = arg[1]

if not rune then
    os.exit(1)
end

local command = actions.click[rune]

if command then
    os.execute(command)
end
