#!/usr/bin/env lua

local home = os.getenv("HOME")
package.path = package.path .. ";" .. home .. "/.config/creek/?.lua"

local actions = require("modules.actions")

local rune = arg[1]
local direction = arg[2]

if not rune or not direction then
    os.exit(1)
end

local command = actions.scroll[rune .. ":" .. direction]

if command then
    os.execute(command)
end
